version: 1.0
service_name: nepal-common

stages:
    -
        name: PR Test
        when:
            - pull_request
        image: node:13
        compute_size: small
        commands:
            - npm install
#            - npm install puppeteer
#            - export CHROME_BIN=$(node -e "console.log(require('puppeteer').executablePath())")
#            - npm run test
            - npm run lint
            - npm run build
            - npx madge --circular --extensions ts --ts-config tsconfig.json src

    -
        name: Master Push - Publish
        when:
            - push: ['master']
        image: node:13
        compute_size: small
        commands:
            - |
              set -ex
              #git config --global --add url."git@github.com:".insteadOf "https://github.com/"
              
              echo $NPM_TOKEN | base64
              
              echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > .npmrc
              npm whoami
              
              PKGNAME=$(node -e 'console.log(require("./package.json").name)')
              PKGVERSION=$(node -e 'console.log(require("./package.json").version)')
              V_VERSION=v$PKGVERSION
              WORDCOUNT=$(npm view "${PKGNAME}@${PKGVERSION}" | wc -c)
              
              #git tag -a $V_VERSION -m "$PKGNAME release $V_VERSION" HEAD
              
              npm install
              
              if [ "$WORDCOUNT" -eq 0  ]; then
                 echo "PUBLISHING $PKGNAME $PKGVERSION"
                 npm run build
                # git push origin $V_VERSION
                 npm publish --access public
              else
                 echo "NOT PUBLISHING $PKGNAME $PKGVERSION"
              fi
            - echo done
